import streamlit as st

st.set_page_config(
    page_title="Healthcare Recommendation System",
    page_icon="🩺",
    layout="wide"
)

st.title("Healthcare Recommendation System")
st.subheader("AI-Powered Disease Prediction & Healthcare Assistant")

st.write(
    """
Welcome to the **Healthcare Recommendation System**.

This application uses Machine Learning to predict diseases from symptoms,
calculate BMI, assess health risk, and provide medicine and lifestyle
recommendations.
"""
)

st.divider()

st.subheader("System Features")

col1, col2 = st.columns(2)

with col1:
    st.success("Disease Prediction")
    st.success("BMI Calculator")
    st.success("Health Risk Assessment")

with col2:
    st.success("Medicine Recommendation")
    st.success("Analytics Dashboard")
    st.success("Prediction History")

st.divider()

st.subheader("Quick Navigation")

c1, c2 = st.columns(2)

with c1:
    if st.button("Patient Registration", use_container_width=True):
        st.switch_page("pages/1Home.py")

    if st.button("Disease Prediction", use_container_width=True):
        st.switch_page("pages/2Prediction.py")

with c2:
    if st.button("Medicine Recommendation", use_container_width=True):
        st.switch_page("pages/3_Recommendation.py.py")

    if st.button("Analytics Dashboard", use_container_width=True):
        st.switch_page("pages/4_Analytics.py")

st.divider()

st.subheader("Project Overview")

c1, c2, c3 = st.columns(3)

c1.metric("Symptoms", "9")
c2.metric("ML Algorithm", "Random Forest")
c3.metric("Modules", "4")

st.divider()

st.info(
    "This project is developed for educational purposes. "
    "The predictions generated by this application should not be considered "
    "a substitute for professional medical advice."
)

st.caption(
    "Developed by Anjali Jain | Python • Streamlit • Machine Learning"
)